### ISSUE TITLE
Link for documentation does not exist

### ISSUE THREAD

**Issue by poohzrn** [yrke/AAUWebMgmt#1]
The link for `Dokumentation` in onenote refers to a page that does not exist. 

https://docs.its.aau.dk/Documentation/Info%20til%20Service%20Desk/INFO.one#Velkommen%20til%20Info%20til%20Service%20Desk (....) does not exist.
![Screenshot](https://cloud.githubusercontent.com/assets/4310945/13738735/3c4c082c-e9c7-11e5-87b5-a72cdd1d1c4a.PNG)

https://github.com/yrke/AAUWebMgmt/blob/61c2fd55239a15eded3aa26c0a01e72fb04a5755/ITSWebMgmt/Site.Master#L74

**Comment by yrke** [comment]
Fix committed
