### ISSUE TITLE
Querying a user with only one proxy address crashes the website

### ISSUE THREAD

**Issue by ScumbagDog** [yrke/AAUWebMgmt#23]
Looking up a user doesn't always show all the info it should. This should be fixed

**Comment by yrke** [comment]
seems to be student

**Comment by ScumbagDog** [comment]
This seems to be related to user.ProxyAddresses in UserController.cs (line 31) where the addresses are not cast to anything and instead returns an unhandled exception, as it could return either an array of strings or a single string
